create table if not exists public.books (
  id bigint generated by default as identity primary key,
  type text not null default 'Livro',
  title text not null,
  category text not null default '',
  gtin text not null default '',
  brand text not null default '',
  condition text not null default 'Usado',
  condition_detail text not null default '',
  condition_notes text not null default '',
  publisher text not null default '',
  language text not null default 'Português',
  origin text not null default 'Nacional',
  isbn text not null default '',
  edition_type text not null default '',
  cover_type text not null default '',
  quantity integer not null default 1,
  year text not null default '',
  package_size text not null default '',
  custom_product boolean not null default false,
  package_quantity integer not null default 1,
  editor text not null default '',
  translator text not null default '',
  version text not null default '',
  author text not null default '',
  description text not null default '',
  price_cents integer not null default 0,
  stock integer not null default 1,
  sku text not null default '',
  weight_kg numeric(10, 3) not null default 0.3,
  width_cm numeric(10, 2) not null default 16,
  length_cm numeric(10, 2) not null default 23,
  height_cm numeric(10, 2) not null default 3,
  photo_url text not null default '',
  media jsonb not null default '[]'::jsonb,
  subject text not null default '',
  course_origin text not null default '',
  collection_id text,
  collection_name text,
  collection_volume integer,
  collection_total_volumes integer,
  collection_discount_pct integer,
  status text not null default 'available' check (status in ('available', 'sold', 'reserved')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists books_status_created_at_idx on public.books (status, created_at desc);
create index if not exists books_category_idx on public.books (category);
create index if not exists books_type_idx on public.books (type);
create index if not exists books_subject_idx on public.books (subject);
create index if not exists books_collection_id_idx on public.books (collection_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_books_updated_at on public.books;
create trigger set_books_updated_at
before update on public.books
for each row
execute function public.set_updated_at();

insert into storage.buckets (id, name, public)
values ('book-images', 'book-images', true)
on conflict (id) do update set public = excluded.public;
